[theme]

# Primary accent for interactive elements
primaryColor = '#A569BD'

# Background color for the main content area
backgroundColor = '#3C0854'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#FDC504'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"